<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<PackageDir>$(ProjectDir)Package</PackageDir>
	</PropertyGroup>
	<Target Name="CreateMdbFile" BeforeTargets="CopyDLLToPlugins" Condition="'$(Configuration)' == 'Debug'">
		<Message Text="Creating the mdb debug file" Importance="high" Condition="Exists('$(Pdb2MdbPath)')" />
		<Delete Files="$(TargetPath).mdb" />
		<Exec Command="$(Pdb2MdbPath) $(TargetPath)" Condition="Exists('$(Pdb2MdbPath)')" />
		<Message Text="Creation succeeded" Importance="high" Condition="'$(MSBuildLastTaskResult)' == 'True' AND Exists('$(TargetPath).mdb')" />
	</Target>

	<Target Name="CopyDLLToPlugins" AfterTargets="$(AfterTargets)" Condition="'$(Configuration)' == 'Debug'">
		<Message Text="Copying DLL file to plugins" Importance="high" />
		<MakeDir Directories="$(MOD_DEPLOYPATH)\$(AssemblyName)" />
		<Message Text="Copying $(TargetFileName) to $(MOD_DEPLOYPATH)\$(AssemblyName)" Importance="high" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MOD_DEPLOYPATH)\$(AssemblyName)" />
		<Message Text="Copying $(TargetFileName).mdb to $(MOD_DEPLOYPATH)\$(AssemblyName)" Importance="high" Condition="Exists('$(TargetPath).mdb')" />
		<Copy SourceFiles="$(TargetPath).mdb" DestinationFolder="$(MOD_DEPLOYPATH)\$(AssemblyName)" Condition="Exists('$(TargetPath).mdb')" />
		<Message Text="Copying $(AssemblyName).pdb to $(MOD_DEPLOYPATH)\$(AssemblyName)" Importance="high" Condition="Exists('$(TargetDir)$(AssemblyName).pdb')" />
		<Copy SourceFiles="$(TargetDir)$(AssemblyName).pdb" DestinationFolder="$(MOD_DEPLOYPATH)\$(AssemblyName)" Condition="Exists('$(TargetDir)$(AssemblyName).pdb')" />
		<Message Text="Copy succeeded" Importance="high" />
	</Target>

	<Target Name="CopyDLLToServer" AfterTargets="CopyDLLToPlugins" Condition="'$(Configuration)' == 'Debug' And '$(CopyToServer)' == 'true'">
		<Message Text="Copying DLL file to server" Importance="high" />
		<MakeDir Directories="$(SERVER_DEPLOYPATH)\$(AssemblyName)" />
		<Message Text="Copying $(TargetFileName) to $(SERVER_DEPLOYPATH)\$(AssemblyName)" Importance="high" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SERVER_DEPLOYPATH)\$(AssemblyName)" />
		<Message Text="Copying $(TargetFileName).mdb to $(SERVER_DEPLOYPATH)\$(AssemblyName)" Importance="high" Condition="Exists('$(TargetPath).mdb')" />
		<Copy SourceFiles="$(TargetPath).mdb" DestinationFolder="$(SERVER_DEPLOYPATH)\$(AssemblyName)" Condition="Exists('$(TargetPath).mdb')" />
		<Message Text="Copying $(AssemblyName).pdb to $(SERVER_DEPLOYPATH)\$(AssemblyName)" Importance="high" Condition="Exists('$(TargetDir)$(AssemblyName).pdb')" />
		<Copy SourceFiles="$(TargetDir)$(AssemblyName).pdb" DestinationFolder="$(SERVER_DEPLOYPATH)\$(AssemblyName)" Condition="Exists('$(TargetDir)$(AssemblyName).pdb')" />
		<Message Text="Copy succeeded" Importance="high" />
	</Target>
</Project>
